# Generated by Django 4.2.21 on 2025-05-22 14:41

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=150, null=True)),
                ("article_url", models.URLField(max_length=1024, unique=True)),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("published_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the country (e.g., New Zealand).", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Two-letter ISO country code (e.g., 'nz').", max_length=2, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "api_id",
                    models.CharField(
                        help_text="The identifier for the source from NewsAPI.org (e.g., 'bbc-news').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The display name of the news source (e.g., BBC News).", max_length=150),
                ),
                ("description", models.TextField(blank=True, help_text="A description of the source.", null=True)),
                (
                    "url",
                    models.URLField(blank=True, help_text="The homepage URL of the source.", max_length=500, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="The category of the source (e.g., technology, sports).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, help_text="The language of the source (e.g., en).", max_length=10, null=True
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, help_text="The country this source is primarily from.", max_length=2, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "keywords",
                    models.JSONField(default=api.models.get_default_keywords, help_text="List of preferred keywords."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_countries",
                    models.ManyToManyField(
                        blank=True, help_text="User's preferred countries for news.", to="api.country"
                    ),
                ),
                (
                    "preferred_sources",
                    models.ManyToManyField(blank=True, help_text="User's preferred news sources.", to="api.source"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_read", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users_in_feed", to="api.article"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-article__published_at"],
                "unique_together": {("user", "article")},
            },
        ),
    ]
