# Generated by Django 4.2.21 on 2025-05-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_article_country_source_user_bio_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="api.country",
            ),
        ),
    ]
