# Generated by Django 4.2.21 on 2025-05-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_source_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userarticle",
            name="is_read",
        ),
    ]
