# Generated by Django 4.2.21 on 2025-05-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_userarticle_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="api.source",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="article_url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="source_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.TextField(),
        ),
    ]
