# Generated by Django 4.2.21 on 2025-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_article_source_alter_article_article_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
