# Generated by Django 4.2.21 on 2025-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_url",
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
