# Generated by Django 4.2.21 on 2025-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_article_article_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
